<?PHP 

$lista_produtos = [
    [
        "id" => 1,
        "nome" => "Produto 1",
        "descricao" => "Descrição do produto 1",
        "quantidade" => 10,
        "valor" => 10.00,
        "imagem" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fbr%2Fvetor%2Fvetor-de-embalagem-de-caixa-de-papel-de-presente-gm1130005789-298759459&psig=AOvVaw0QZ3Z4Q4Z3Q8Q4Q4Q4Q4Q4&ust=1623686168212000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjQ4ZqH0_ECFQAAAAAdAAAAABAD",
    ],
    [
        "id" => 2,
        "nome" => "Produto 2",
        "descricao" => "Descrição do produto 2",
        "quantidade" => 20,
        "valor" => 20.00,
        "imagem" => "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.istockphoto.com%2Fbr%2Fvetor%2Fvetor-de-embalagem-de-caixa-de-papel-de-presente-gm1130005789-298759459&psig=AOvVaw0QZ3Z4Q4Z3Q8Q4Q4Q4Q4Q4&ust=1623686168212000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJjQ4ZqH0_ECFQAAAAAdAAAAABAD",
    ],
    [
        "id" => 3,
        "nome" => "Produto 3",
        "descricao" => "Descrição do produto 3",
        "quantidade" => 30,
        "valor" => 30.00,
    ],
    [
        "id" => 4,
        "nome" => "Produto 4",
        "descricao" => "Descrição do produto 4",
        "quantidade" => 40,
        "valor" => 40.00,
    ],
    [
        "id" => 5,
        "nome" => "Produto 5",
        "descricao" => "Descrição do produto 5",
        "quantidade" => 50,
        "valor" => 50.00,
    ]
];


?>