<?PHP 

$lista_produtos = [
    [
        "id" => 1,
        "nome" => "Produto 1",
        "descricao" => "Descrição do produto 1",
        "quantidade" => 10,
        "valor" => 10.00,
    ],
    [
        "id" => 2,
        "nome" => "Produto 2",
        "descricao" => "Descrição do produto 2",
        "quantidade" => 20,
        "valor" => 20.00,
    ],
    [
        "id" => 3,
        "nome" => "Produto 3",
        "descricao" => "Descrição do produto 3",
        "quantidade" => 30,
        "valor" => 30.00,
    ],
    [
        "id" => 4,
        "nome" => "Produto 4",
        "descricao" => "Descrição do produto 4",
        "quantidade" => 40,
        "valor" => 40.00,
    ],
    [
        "id" => 5,
        "nome" => "Produto 5",
        "descricao" => "Descrição do produto 5",
        "quantidade" => 50,
        "valor" => 50.00,
    ]
];


?>